config/routes.rb
Apalka::Application.routes.draw do
  resources :operations

  get "register/index"
  post "register/index"
  get "register/registred"

  get "applicationblank/index"

  get "applicationblank/post"
  post "applicationblank/post"

  
  resources :messages

  get "login/index"

  get "login/login"
  post "login/login"
  get "login/logout"

end

app/models/message.rb
class Message < ActiveRecord::Base

  def self.is_valid_message(user_id, message_id)
    #
    message= self.find_by_id(message_id)
    if message
      expected_user_id= message.user_id
      if expected_user_id.to_s!= user_id.to_s
        message= nil
      end
    end
    message
  end

#
#    def self.is_valid_shop(user_id, shop_id)
#   ## product= self.find_by_id(product_id)
#    shop= self.find_by_id(shop_id)
#    if shop
#      expected_user_id= shop.user_id
#      if expected_user_id.to_s!= user_id.to_s
#        shop= nil
#      end
#    end
#    shop
#  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authorize, :except => :login

  # GET /messages
  # GET /messages.xml
  #главная страница
  def index
    user_id= session[:user_id]
    @messages = Message.find(:all, :conditions=>"user_id="+user_id.to_s)
    @user= admin_flag(user_id)
    #@money= session[:user_money]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    user_id= session[:user_id]
    message_id= params[:id]
    if Message.is_valid_message(user_id, message_id)
      @message = Message.find(message_id)
      @user= admin_flag(user_id)
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @message }
      end
    else
      @message= nil
      redirect_to :action=>'index'
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    user_id= session[:user_id]
    message_id= params[:id]
    if Message.is_valid_message(user_id, message_id)
      @message = Message.find(message_id)
      @user= admin_flag(user_id)
    else
      @message= nil
      redirect_to :action=>'index'
    end
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])
    @message.user_id= session[:user_id]
    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    user_id= session[:user_id]
    message_id= params[:id]
    if Message.is_valid_message(user_id, message_id)
      @message = Message.find(message_id)
      respond_to do |format|
        if @message.update_attributes(params[:message])
          format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
        end
      end
    else
      @message= nil
      redirect_to :action=>'index'
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    user_id= session[:user_id]
    message_id= params[:id]
    if Message.is_valid_message(user_id, message_id)
      @message = Message.find(params[:id])
      @message.destroy
      respond_to do |format|
        format.html { redirect_to(messages_url) }
        format.xml  { head :ok }
      end
    else
      @message= nil
      redirect_to :action=>'index'
    end
  end

  private
  def admin_flag(user_id)
    if User.isadmin(user_id)
      return true
    else
      return false
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user %>
    <div class="field">
      <%= f.label :start %><br />
      <%= f.datetime_select :start %>
    </div>
    <div class="field">
      <%= f.label :stop %><br />
      <%= f.datetime_select :stop %>
    </div>

  <div class="field">
    <%= f.label :every %><br />
    <%= f.text_field :every %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :msg %><br />
    <%= f.text_field :msg %>
  </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :phone %><br />
      <%= f.text_field :phone %>
    </div>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :pass %><br />
    <%= f.text_field :pass %>
  </div>
  <div class="field">
    <%= f.label :allowed %><br />
    <%= f.check_box :allowed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%end%>


<table border="0">
  <tr>
    <td>Адрес объявления </td><td><%= f.text_field :url, :class => "input", :size=>"70"%></td>
  </tr>
  <tr>
    <td>Текст сообщения</td><td><%= f.text_field :msg, :class => "input"%></td>
  </tr>
  <tr>
    <td>Логин для форума</td><td><%= f.text_field :login , :class => "input"%></td>
  </tr>
  <tr>
    <td>Пароль для форума</td><td><%= f.text_field :pass , :class => "input"%></td>
  </tr>
  <tr>
    <td>Обновлять раз в</td><td><%= f.text_field :every, :class => "input"%></td>
  </tr>
    <tr>
    <td>Активировать</td><td><%= f.check_box :allowed %></td>
  </tr>
  <tr>
    <td></td><td><%= submit_tag "Записать", :class => "submit" %></td>
  </tr>
</table>
<% end %>

app/views/messages/edit.html.erb
<h1>Редактирование темы</h1>

<%= render 'form' %>

<%= link_to 'Показать', @message %> |
<%= link_to 'Вернуться', messages_path %>

app/views/messages/index.html.erb
<%= link_to 'Новая тема', new_message_path %>
<table border="1">
  <tr>
    <% if @user %><th>Пользователь</th>
    <th>Старт</th>
    <th>Стоп</th>
    <%end%>
    <th>Обновлять каждые</th>
    <th>Адрес</th>
    <th>Текст сообщения</th>
    <%if @user%>
    <th>Email</th>
    <th>Телефон</th>
    
    <th>Логин для форума</th>
    <th>Пароль для форума</th>
    <%end%>
    <th>Активность</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <%if @user%>
    <td><%= message.user_id %></td>
    <td><%= message.start %></td>
    <td><%= message.stop %></td>
    <%end%>
    <td><%= message.every %></td>
    <td><%= message.url %></td>
    <td><%= message.msg %></td>
    <%if @user%>
    <td><%= message.email %></td>
    <td><%= message.phone %></td>
    
    <td><%= message.login %></td>
    <td><%= message.pass %></td>
    <%end%>
    <td><%= message.allowed %></td>
    <td><%= link_to 'Показать', message %></td>
    <td><%= link_to 'Ред.', edit_message_path(message) %></td>
    <td><%= link_to 'Удалить', message, :confirm => 'Серьезно удалить?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая тема', new_message_path %>

app/views/messages/new.html.erb
<h1>Новая тема</h1>

<%= render 'form' %>

<%= link_to 'Вернуться', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<% if @user %>
<p>
  <b>Старт:</b>
  <%= @message.start %>
</p>

<p>
  <b>Стоп:</b>
  <%= @message.stop %>
</p>
<%end%>
<p>
  <b>Частота:</b>
  <%= @message.every %>
</p>

<p>
  <b>Адрес:</b>
  <%= @message.url %>
</p>

<p>
  <b>Текст сообщения:</b>
  <%= @message.msg %>
</p>
<% if @user %>
<p>
  <b>Email:</b>
  <%= @message.email %>
</p>

<p>
  <b>Телефон:</b>
  <%= @message.phone %>
</p>
<%end%>
<p>
  <b>Логин для форума:</b>
  <%= @message.login %>
</p>

<p>
  <b>Пароль для форума:</b>
  <%= @message.pass %>
</p>

<p>
  <b>Активность:</b>
  <%= @message.allowed %>
</p>


<%= link_to 'Редактировать', edit_message_path(@message) %> |
<%= link_to 'Вернуться', messages_path %>