config/routes.rb
Apalka::Application.routes.draw do
  resources :operations

  get "register/index"
  post "register/index"
  get "register/registred"

  get "applicationblank/index"

  get "applicationblank/post"
  post "applicationblank/post"

  
  resources :messages

  get "login/index"

  get "login/login"
  post "login/login"
  get "login/logout"

end

app/models/operation.rb
class Operation < ActiveRecord::Base
 # cattr_reader :per_page
 
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_filter :authorize, :except => :login
  # GET /operations
  # GET /operations.xml
  def index
    user_id= session[:user_id]
    
  #  @operations = Operation.find(:all, :conditions=>"user_id="+user_id.to_s)
    @operations = Operation.paginate(:all, :conditions=>"user_id="+user_id.to_s, :page=> params[:page],:per_page => 20)
  

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @operations }
    end
  end

  # GET /operations/1
  # GET /operations/1.xml
#  def show
#    @operation = Operation.find(params[:id])
#
#    respond_to do |format|
#      format.html # show.html.erb
#      format.xml  { render :xml => @operation }
#    end
#  end

#  private
#  def admin_flag(user_id)
#    if User.isadmin(user_id)
#      return true
#    else
#      return false
#    end
#  end

  #  # GET /operations/new
  #  # GET /operations/new.xml
  #  def new
  #    @operation = Operation.new
  #
  #    respond_to do |format|
  #      format.html # new.html.erb
  #      format.xml  { render :xml => @operation }
  #    end
  #  end
  #
  #  # GET /operations/1/edit
  #  def edit
  #    @operation = Operation.find(params[:id])
  #  end
  #
  #  # POST /operations
  #  # POST /operations.xml
  #  def create
  #    @operation = Operation.new(params[:operation])
  #
  #    respond_to do |format|
  #      if @operation.save
  #        format.html { redirect_to(@operation, :notice => 'Operation was successfully created.') }
  #        format.xml  { render :xml => @operation, :status => :created, :location => @operation }
  #      else
  #        format.html { render :action => "new" }
  #        format.xml  { render :xml => @operation.errors, :status => :unprocessable_entity }
  #      end
  #    end
  #  end
  #
  #  # PUT /operations/1
  #  # PUT /operations/1.xml
  #  def update
  #    @operation = Operation.find(params[:id])
  #
  #    respond_to do |format|
  #      if @operation.update_attributes(params[:operation])
  #        format.html { redirect_to(@operation, :notice => 'Operation was successfully updated.') }
  #        format.xml  { head :ok }
  #      else
  #        format.html { render :action => "edit" }
  #        format.xml  { render :xml => @operation.errors, :status => :unprocessable_entity }
  #      end
  #    end
  #  end
  #
  #  # DELETE /operations/1
  #  # DELETE /operations/1.xml
  #  def destroy
  #    @operation = Operation.find(params[:id])
  #    @operation.destroy
  #
  #    respond_to do |format|
  #      format.html { redirect_to(operations_url) }
  #      format.xml  { head :ok }
  #    end
  #  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :message_id %><br />
    <%= f.text_field :message_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :msg %><br />
    <%= f.text_area :msg %>
  </div>
  <div class="field">
    <%= f.label :every %><br />
    <%= f.text_field :every %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br />
    <%= f.datetime_select :datetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<h2>Список операций</h2>
<%= will_paginate @operations %>
<table>
  <tr>
    <th>Адрес на сайте</th>
    <th>Сообщение</th>
    <th>Частота</th>
    <th>Стоимость</th>
    <th>Время</th>

  </tr>

<% @operations.each do |operation| %>
  <tr>

    <td><%= operation.url %></td>
    <td><%= operation.msg %></td>
    <td><%= operation.every %></td>
    <td><%= operation.price %></td>
    <td><%= operation.datetime %></td>

  </tr>
<% end %>
</table>
<%= will_paginate @operations %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @operation.user_id %>
</p>

<p>
  <b>Message:</b>
  <%= @operation.message_id %>
</p>

<p>
  <b>Url:</b>
  <%= @operation.url %>
</p>

<p>
  <b>Msg:</b>
  <%= @operation.msg %>
</p>

<p>
  <b>Every:</b>
  <%= @operation.every %>
</p>

<p>
  <b>Price:</b>
  <%= @operation.price %>
</p>

<p>
  <b>Datetime:</b>
  <%= @operation.datetime %>
</p>


<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>